### ISSUE TITLE
its weird (and not documented) that you have to new up featureservice objects

### ISSUE THREAD

**Issue by jgravois** [Esri/geoservices-js#101]
samples show

``` js
client.featureservice( params , function (err, result) {
```

but `new` is actually [required](https://github.com/Esri/geoservices-js/blob/master/test/featureservice-test.js#L17).

``` js
new client.featureservice( params , function (err, result) {
```

looking for enlightenment (most likely from @nixta)

**Comment by jgravois** [comment]
even weirder, the tests that previously didn't have new (94b1c29d3f134812bed70aa35fb15368a3ce43bf) didn't fail from my other computer.
not sure what else could explain it besides my version of node?

i'm running `4.2.2`  on this computer.

**Comment by nixta** [comment]
iirc I was surprised by this when I wrote the [esri-gnip](https://github.com/Esri/esri-gnip/blob/master/index.js#L230) code too.

**Comment by jwasilgeo** [comment]
Not sure either, but I also encountered this problem and a few months back did the following:

```javascript
// This was a little funny, but after 0.5 year has passed I can't remember why I did it. :-D
const EsriFeatureService = require('geoservices/lib/featureservice').FeatureService;

const myFeatureService = new EsriFeatureService(params, (error, result) => {...});
```
