### ISSUE TITLE
Error when using `client.options.geocoderUrl`

### ISSUE THREAD

**Issue by gavinr** [Esri/geoservices-js#112]
I get this error when following the example in [this documentation](https://github.com/Esri/geoservices-js/blob/master/docs/Geocoding.md#passing-additional-parameters):

```
const client = new Geoservices();
client.options.geocoderUrl = 'https://my.geocoder.com/a/rest/services/Locators/AddressPointLocator/GeocodeServer';
client.geocode({.....}, function() { ... });
```

```
TypeError: Cannot set property 'geocoderUrl' of undefined
```

It seems like the solution is to create an object off of my `client` object first. For example, this seems to work fine:

```
const client = new Geoservices();
client.options = {};
client.options.geocoderUrl = 'https://my.geocoder.com/a/rest/services/Locators/AddressPointLocator/GeocodeServer';
client.geocode({.....}, function() { ... });
```

I'm not sure if I'm doing something wrong, or if we should add that line (`client.options = {};`) to the documentation, or if we should change the module so that line is not required. Looking for input. Thanks!

**Comment by jgravois** [comment]
if you're interested in submitting a pull request to ensure that an empty options object is created automatically when the class is instantiated, i'd be happy to make sure it gets landed, but i think it'd be sufficient to just update the doc to demonstrate the same technique we use in the test suite.

https://github.com/Esri/geoservices-js/blob/261b29a8ac87a580377fa3011f31a1ebad795503/test/geocode-test.js#L126
