### ISSUE TITLE
Chainable query class for FeatureService

### ISSUE THREAD

**Issue by patrickarlt** [Esri/geoservices-js#33]
I walk talking with @mpriour  about this it would be great to have a class that would abstract the complexities of querying a feature service. 

Here was the example I gave @mpriour.

`Query().within(extent).where({"city": "Portland"})`

We could also hang this off `FeatureService`.

``` js
query = new client.FeatureService.Query().within(extent).where({"city": "Portland"});

myFeatureService.query(query, callback);
```

**Comment by ajturner** [comment]
I'm curious where this ended up. Seems to have derailed on pagination.

I'm interested in the original topic of a chainable, relational algebra, type of api. Very similar to [Arel](https://github.com/rails/arel).

This type of API would be easier to work with and also enable currying. Anyone want to help move it forward?
