### ISSUE TITLE
geocode.batch() overwriting OBJECTID

### ISSUE THREAD

**Issue by wilsaj** [Esri/geoservices-js#90]
An `OBJECTID` currently gets generated when calling `geocode.batch()` if one isn't passed in as the second argument (`optionalId`). The auto-generated ID is also currently overwriting `OBJECTID` even if it already exists on the object. Example, in the following, `OBJECTID` will replaced by an auto-generated id based on the number of previously calls to `batch()`:
```
  geocode.batch({
    SingleLine: "380 New York Street, Redlands, CA 92373-8100",
    OBJECTID: 4326
  })
```

This was a bit surprising to me - I'd expect the optionalId to overwrite `OBJECTID` only if it doesn't already exist. If both `OBJECTID` exist and `optionalId` is passed but they are different, then maybe throw an error?

**Comment by jgravois** [comment]
seems inappropriate to me.  i'll take a look.

**Comment by jgravois** [comment]
check out my PR.  

> If both `OBJECTID` exist and `optionalId` is passed but they are different, then maybe throw an error?

i don't think we need to bother trapping for that.  i'm hoping/expecting developers will use one or the other.
