### ISSUE TITLE
example which demonstrates how to batch geocode a .csv

### ISSUE THREAD

**Issue by jgravois** [Esri/geoservices-js#95]
i think we need a sample in this repository to demonstrate how to batch geocode from `.csv`'s

maybe its overkill, but i think a full blown browser/node backend heroku app would be a lot more fun than a node script that expects the input to be provided via the commandline.
### requirements:
1. in the browser, direct users to upload a .csv which includes a column named something like `address` that contains the text that needs to be geocoded.
2. give opportunity to sign in using OAuth2 for geocoding more than a few rows.
3. pass back the .csv with a `latitude` and `longitude` field appended.

i should be able to rip off the code @phpmaps wrote [here](https://github.com/Esri/developer-support/tree/master/web-js/batch-geocoding-nodejs).

**Comment by phpmaps** [comment]
John I got one in developer - support . Only minor tweeking is needed.  Feel free to kick the tires with it and port it into this repro.  It's on my list of things to do.  What's cool about the sample is some smart chunk-ing logic useful for big batch jobs.


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by jgravois** [comment]
still want to do this, but lets do it using the new _shiz_
