### ISSUE TITLE
geoservices.js

### ISSUE THREAD

**Issue by lingpri** [Esri/geoservices-js#97]
Hi - I'm trying to use this geoservices.js library with my locally hosted ARCGIS geocoding service.This ARCGIS geocoding service is running on IIS Server , with integrated windows authentication. I see credential errors when running against the locally hosted service. Doing some research, it appears, passport-windowsauth.js. can you help rectify the issue.

```javascript
var Geoservices = require('geoservices');
var request = require('request');

var passport = require('passport');
var WindowsStrategy = require('passport-windowsauth');



passport.use(function(profile, done){
  User.findOrCreate({ waId: profile.id }, function (err, user) {
    done(err, user);
  });
});

app.get('/express-passport',
  passport.authenticate('WindowsAuthentication'),
  function (req, res){
    res.json(req.user);
  });
'''
I get the error , Authentication Strategies must have a name. Please advise.

**Comment by jgravois** [comment]
are you asking for help resolving your problem with `passport-windowsauth` or requesting that we do something additional in this codebase to ensure compatibility?

**Comment by lingpri** [comment]
sorry about not being clear.Yes asking for help to resolve the problem. Also, It would be great to have this geoservices.js to be able to use it with any internally hosted services too , with integrated  windows authentication enabled.

**Comment by jgravois** [comment]
what is your ultimate goal?
are you trying to write a standalone node application which makes authenticated requests to your geocoding service?
are you trying to write your own web application with custom server side code which asks end users for credentials and then passes them through?
if you're already developing a web application, are you using our [jsapi](https://developers.arcgis.com/javascript/jsapi/)?

**Comment by lingpri** [comment]
jgravois - My background is from Flex and we have a web application, that uses our home-grown ArcGIS geocoding service to batch geocode using the SOAP API. we are trying to port the application to JSAPI. I'm thinking if we write a node js module for batchgeocoding, we can re-use it for both client and the server side. Please advise. The answer is "YES" to all your questions 1)  2) and 3). Apologize for taking a long time to reply.

**Comment by jgravois** [comment]
i guess i really don't understand the purpose of attempting to write server side code to leverage a geocoding service that already provides the functionality for both single and batch requests *out of the box*.

**Comment by JerrySievert** [comment]
@jgravois maybe some sort of CORS requirement?

but passport isn't going to help with geoservices-js.

**Comment by jgravois** [comment]
closing, but happy to chat more if more information is provided.

**Comment by lingpri** [comment]
I was able to successfully access in-house geocoding service, using the Java proxy and this library. Thanks for looking into this.
