### ISSUE TITLE
Wish: support filtering geocoding to a bounding box.

### ISSUE THREAD

**Issue by markstos** [Esri/geoservices-js#99]
It would be nice if there was an option to specify a bounding box to be used with geocoding, so that results outside the bounding box would be considered geocode failures.

I read the PDF linked into the docs for the upstream REST geocode API being used. It did not have documented support bounding box restriction built in. 

This library could perhaps use [coordinatesContainsPoint](http://terraformer.io/core/#comparisons) to check results as they come back.

**Comment by markstos** [comment]
`<detour>`

It seems that part of is the issue here is that ESRI has several different sets of documentation for the geocoding REST API, and they don't agree with each other. 

[This geocoding API document](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Geocode_Service/02r3000000q9000000/) is linked to from the Geocoding page of the documentation here, but it does not appear to document the "find" method of the geocode server as expecting. 

The README in this distribution links to a [REST API from 2010](http://www.esri.com/library/whitepapers/pdfs/geoservices-rest-spec.pdf) but it does mention a bounding box restriction available for geocode searches. 

However, the competing [gecoder-arcgis](https://github.com/StephanGeorg/geocoder-arcgis) module links to a [third set of documentation for an ArcGIS geocoder REST API](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find.htm)

Only this set of documentation mentions that there's a bbox option for the `find` geocoding method. 

Dealing with 3 sets of API documentation that disagree with each and omit features is seriously frustrating.  

Can you please fix the documentation links here to point to whichever version of  ESRI's documentation is current and correct? It would also be helpful if the other documentation sites were updated to note that they are outdated.

`</detour>`

Back to the `bbox` option: Since the feature does apparently exist upstream, it would great if it was exposed in the code and docs here.

**Comment by jgravois** [comment]
i both understand and apologize for the frustration.

the authoritative documentation for Esri's World Geocoding Service (that actually includes a `find` operation) is:
https://developers.arcgis.com/rest/geocode/api-reference/overview-world-geocoding-service.htm

the authoritative REST documentation for custom geocoding services is:
http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Geocode_Service/02r3000000q9000000/

obviously anything else you find in conflict compounds the problem, but the discrepancy is the result of the fact that the REST spec for custom services is not identical to our own hosted geocoding service so we need to do a better job of linking to both and explaining that they differ.

**Comment by jgravois** [comment]
i put in a PR to get rid of the white paper link and bump up the links that i'd already put in, but buried before.

with regard to `bbox` filtering.  you can do this right now:

```js
client.geocode({
  text: "920 SW 3rd Ave, Portland, OR 97201",
  bbox: "-101,30,-100,31"
}, function (err, result) {
  if (result.locations.length) {
    // remove 'bbox' parameter and a result is returned
    console.log("match found");
  } else {
    console.log("no match found, because portland is near -122, 45");
  }
});
```

are we missing something else you need?

**Comment by markstos** [comment]
@jgravois Thanks for the fast fix.  There are still some related doc improvements that seem important. 

The World and Custom doc links are provided are if they are fairly equal.   However, only the World server provides a `/find` endpoint for "Geocode Service". At least, a parallel method is not mentioned in the Custom docs:

http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Geocode_Service/02r3000000q9000000/

However, the `/find` method is hardcoded into the source code here. So as it stands now, the geocode feature only works with the World server, and thus only the World docs apply.   That should be noted in the docs.  Given this situation, it would be helpful to in-line the docs for `/find` from the World server here so users of the Node.js client here can easily find out about `bbox` and the other goodies`.

https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find.htm#ESRI_SECTION1_E8390AE55A67457A99B5A9E2E3F54FBC

It's easy and reasonable to assume that the options documented here are the only ones that are supported or exist. 

-----

As I read through our own code, it looks like we are using the batch geocoding endpoint, but only gecoding a single address at a time with it. I think there's a reason we are doing that, but I can't recall. :)  Since batch geocoding doesn't support `bbox`, either I need implement it client side, or switch to using the the single-address endpoint and hope I don't rediscover why we are using the batch endpoint. :)

I think I'm going to give a client-side `bbox` filtering at this point and see how that goes.

**Comment by jgravois** [comment]
all good points.

obviously this isn't documented either, but i'm under the impression that custom geocoding services can be accessed by calling `baseUrl()` and passing in your own [`geocoderUrl`](https://github.com/Esri/geoservices-js/blob/master/lib/geocode.js#L15-L17).  that said, i agree with you that current state of the doc leaves *much* to be desired and that the library would be significantly more usable if i (or someone else) took the time to flesh it out.

with regard to single geocodes in batch, i'm not sure why you'd be doing that either, but you can also be a good citizen and authenticate when calling `/find?` by setting [`forStorage=true`](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find.htm) if you're persisting the results in your own datastore. the benefit of this is that it would allow you to pass `bbox` too.

to be perfectly honest, i hardly wrote any of this code and i haven't tested the suggestion i'm making so if there are any gotchas, *please* let me know.

**Comment by markstos** [comment]
@jgravois You are right that there's an option to use a custom geocodeUrl, but appending `/find` to it is hardcoded.  So it seems the docs for the "simple" geocoder should be updated to reflect that the method only works against the World server, not custom servers. 

I did some `git` archeology and figured out our own case. Our code pre-dates the 1.0.0 release of this module, which added support for `find`. At this point, the refactor is more time-consuming as we have a function or two that expect our single-item and batch geocoding cases to return the same format, but `/find` and `/geocodeAddresses` return different data structures for a single item. That bigger refactor is still idea for us in the long term, but for now I think I'm going to try a faster-for-now solution of implementing our own bbox filtering using Terraformer once results are returned. 

This fellow is doing solid work on an alternate geocoding client. Perhaps he could be convinced collaborate on this project: https://github.com/StephanGeorg/geocoder-arcgis

**Comment by jgravois** [comment]
another confusing twist is that `/find` *can* be found as an undocumented functioning operation on some [custom geocoding services](http://sampleserver6.arcgisonline.com/arcgis/rest/services/Locators/Composite_HBR_Asset/GeocodeServer/find) too.  i'll take a stab at making more sense of the insensible in the doc here sometime soon and leave this issue open for now as a reminder.

i agree that @StephanGeorg's project looks great and any contributions he's interested in making here would be *sincerely* appreciated.  and thank you too @markstos.  your feedback is *always* appreciated.

**Comment by StephanGeorg** [comment]
Thanks @jgravois. When I started developing the geocoder-arcgis I wanted a simple and lightweight node.js wrapper **based on promises**. And I wanted to support of all features and optional params. And I think that's the problem of geoservices-js. 

I agree, the documentation of the api is very confusing ;)

**Comment by jgravois** [comment]
> I think that's the problem of geoservices-js...

as far as i know we **do** support all the features and optional request parameters. its just not clear enough in the current state of the documentation.

**Comment by jgravois** [comment]
> @markstos: You are right that there's an option to use a custom geocodeUrl, but appending `/find` to it is hardcoded.

this api now exclusively makes use of `findAddressCandidates` and I pushed [samples](https://github.com/Esri/geoservices-js/blob/master/docs/Geocoding.md#simple-geocoding) which show how to: 

1. make a simple geocoding request
2. append additional parameters (like `searchExtent`)
3. make a geocoding request to a custom geocoding service

hopefully this will make things less opaque for folks in the future.
